'use client';

import Navbar from  "../components/navbar";
import Footer from "../components/footer";  
import './page.css';


export default function TermsAndConditions(){

  return (
    <div className="termsandconditions">
        <Navbar />
        <div className="termsandconditions-container">
            <h1 className="h1">Terms and Conditions</h1>
            <h2 className="h2_1">Effective Date: 17.09.2025</h2>
            <div className="txt">
                Forever Life provides this website to you, 
                the user, subject to the following Terms and
                 Conditions (“Terms”). By accessing or using the
                  website, you agree to be bound by these Terms.
                   If you do not agree, you must not access or 
                   use the App.
            </div>
            <h2 className="h2">1. Description of the App</h2>
            <div className="txt">
                The App utilizes artificial intelligence 
                technology, including OpenAI`s ChatGPT, 
                \to provide informational guidance regarding 
                products that may support certain health or 
                wellness goals. The App also contains affiliate 
                links to products offered by Forever Living 
                Products. Purchases made via these links may 
                result in the Company receiving a commission 
                at no additional cost to you.

            </div>
            <h2 className="h2">2. No Medical Advice</h2>
            <div className="txt">
                
                The App is not intended to provide medical advice,
                 diagnosis, or treatment. All content generated by
                  the App is for informational purposes only. You 
                  should always consult a licensed healthcare 
                  provider regarding any medical condition, 
                  treatment, or product suitability. Reliance 
                  on information provided by the App is solely 
                  at your own risk.
            </div>
            <h2 className="h2">3. Affiliate Disclosure</h2>
            <div className="txt">
                Certain links within the App are affiliate links.
                If you make a purchase via these links,
                 the Company may earn a commission.
                The Company does not guarantee the effectiveness,
                 safety, or suitability of any product.
            </div>
            <h2 className="h2">4. Eligibility</h2>
            <div className="txt">
                
            By using the App, you represent and warrant that
             you are at least 18 years of age, or the age of 
             majority in your jurisdiction, and have the legal
              capacity to enter into these Terms.
            You agree to use the App in compliance with all
             applicable laws and regulations.
            </div>
            <h2 className="h2">5. User Conduct</h2>
            <div className="txt">
                You agree not to:
                <ol className="ol">
                    <li>Reverse engineer, decompile, or attempt
                         to extract the source code of the App;
                    </li>
                    <li>
                        Use the App for any unlawful or fraudulent 
                        purposes;
                    </li>
                    <li>
                        Interfere with, disrupt, or attempt to
                         gain unauthorized access to the App or
                          its servers;
                    </li>
                    <li>
                        Use the App in any manner that could 
                        damage, disable, or impair the App`s 
                        functionality.
                    </li>
                </ol>
            </div>
            <h2 className="h2">6. Limitation of Liability</h2>
            <div className="txt">
                To the maximum extent permitted by law:
                <ul className="ul">
                    <li>
                        The Company, its affiliates, officers, directors, employees, and agents shall not be liable for any direct, indirect, incidental, consequential, or punitive damages arising from your use of the App, reliance on information provided by the App, or purchases made through affiliate links.
                    </li>
                    <li>
                        The App is provided “as is” and “as available,” without warranties of any kind, either express or implied.
                    </li>
                </ul>
            </div>
            <h2 className="h2">7. Intellectual Property</h2>
            <div className="txt">
                All content, materials, and intellectual property 
                contained in the App, including but not limited 
                to text, graphics, logos, AI-generated content, 
                and software, are the property of the Company 
                or its licensors. You may not copy, reproduce,
                 modify, distribute, or create derivative works 
                 from any content in the App without prior
                  written consent from the Company.
            </div> 
            <h2 className="h2">8. Privacy</h2>
            <div className="txt">
                Your use of the App is subject to our Privacy 
                Policy, which explains how we collect, use, 
                and protect your personal information. By using 
                the App, you agree to our Privacy Policy.
            </div>
            <h2 className="h2">9. Modifications</h2>
            <div className="txt">
                The Company reserves the right, at its sole 
                discretion, to modify or replace these Terms 
                at any time. Changes will be effective 
                immediately upon posting within the App. 
                Continued use of the App constitutes acceptance 
                of the modified Terms.
            </div>
            <h2 className="h2">10. Governing Law</h2>
            <div className="txt">
                These Terms shall be governed by and construed
                 in accordance with the laws of Romania, without 
                 regard to its conflict of laws provisions.
            </div>
            <h2 className="h2">11. Contact Information</h2>
            <div className="txt">
                If you have any questions or concerns about 
                these Terms, please contact us at support@forever-life.org 
            </div>
        </div>
        <Footer />
    </div>
  )
}    

